version: "3.8"

services:
  learnit:
    container_name: learnit
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - mariadb_net
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - TZ=Asia/Seoul
    volumes:
      - ~/deploy/learnit/uploaded:/uploaded

networks:
  mariadb_net:
    external: true
