spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  # jpa설정
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update

# 로그 레벨 설정
logging:
  level:
    org.hibernate.SQL: off
    org.hibernate.type: off # 실제 들어가는 파라미터값 찍어주는 설정

jwt:
  secret: ${JWT_SECRET_KEY} # base64 encoded & len > 32 여야함
  access-token-expiration-minutes: ${JWT_ACCESS_TOKEN_EXPIRATION_MINUTES:30}
  refresh-token-expiration-weeks: ${JWT_REFRESH_TOKEN_EXPIRATION_WEEKS:2}

cache:
  specs:
    refresh-token-uuid:
      expiration-week: ${JWT_REFRESH_TOKEN_EXPIRATION_WEEKS:2}
      maximum-size: 10000

gemini:
  api-key: ${GEMINI_API_KEY}

# Gemini flash 2.0 기준 1M TPM
# N번째 시도에서 1분 안에 토큰 초과 시 실패에 따른 재시도 로직 구현을 위한 설정
llm:
  tpm:
    capacity:1000000