spring:
  profiles:
    active: remote
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# 로그 레벨 설정
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace # 실제 들어가는 파라미터값 찍어주는 설정

server:
  port: 8080

  tomcat:
    max-part-count: 100
    max-part-header-size: 2048

file:
  save-path: ./upload

gemini:
  api-key: ${GEMINI_API_KEY}

springdoc:
  swagger-ui:
    validator-url: ""
    url: /v3/api-docs
    config-url: ""
  api-docs:
    path: /v3/api-docs