name: Build Backend with Remote Frontend and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch: # for manual triggers
  repository_dispatch:
    types: [frontend-update]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Backend Repository
      - name: Checkout Backend Repository
        uses: actions/checkout@v4

      # 2. Checkout Frontend Repository
      - name: Checkout Frontend Repository
        uses: actions/checkout@v4
        with:
          repository: DEPthes/4th-MVP-LearningCrew-Web
          path: frontend
          ref: develop

      # 3. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # 4. Cache npm dependencies
      - name: Cache npm dependencies
        uses: actions/cache@v4
        id: npm-cache
        with:
          path: |
            ~/.npm
            frontend/node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      # 5. Install & Build Frontend using npm
      - name: Build Frontend
        working-directory: ./frontend
        run: |
          npm ci
          npm run build

      # 7. Copy frontend build to Spring Boot static resources
      - name: Copy frontend build to Spring Boot static
        run: |
          echo "Copying frontend build from $(pwd)/frontend/dist to $(pwd)/src/main/resources/static"
          rm -rf ./src/main/resources/static/*
          mkdir -p ./src/main/resources/static
          cp -r ./frontend/dist/* ./src/main/resources/static/

      # 8. Setup Java
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      # 9. Cache Gradle packages
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 10. Make Gradle executable
      - name: Make Gradle executable
        run: chmod +x ./gradlew

      # 11. Build Spring Boot JAR
      - name: Build JAR
        run: ./gradlew bootJar

      # 12. Install sshpass
      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      # 13. Register Remote SSH Host
      - name: Register SSH Host
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p ${{ secrets.SERVER_PORT }} ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      # 14. Prepare Directories on Remote
      - name: Prepare Remote Directories
        run: |
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh -p ${{ secrets.SERVER_PORT }} ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "
            mkdir -p /home/learnit &&
            mkdir -p /home/learnit/docker-compose
          "

      # 15. Transfer Files to Remote
      - name: Send app.jar and Dockerfile
        run: |
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" scp -P ${{ secrets.SERVER_PORT }} build/libs/*.jar ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/home/learnit/docker-compose/app.jar
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" scp -P ${{ secrets.SERVER_PORT }} Dockerfile ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/home/learnit/docker-compose/Dockerfile

      # 16. Create .env.prod from secret
      - name: Create .env.prod from secret
        run: |
          echo "DB_HOST=${{ secrets.ENV_DB_HOST }}" >> .env.prod
          echo "DB_NAME=${{ secrets.ENV_DB_NAME }}" >> .env.prod
          echo "DB_USERNAME=${{ secrets.ENV_DB_USERNAME }}" >> .env.prod
          echo "DB_PASSWORD=${{ secrets.ENV_DB_PASSWORD }}" >> .env.prod
          echo "DB_PORT=${{ secrets.ENV_DB_PORT }}" >> .env.prod
          echo "JWT_SECRET_KEY=${{ secrets.ENV_JWT_SECRET_KEY }}" >> .env.prod
          echo "DEPLOY_PATH=${{ secrets.ENV_DEPLOY_PATH }}" >> .env.prod

      # 17. Transfer docker-compose.prod.yml and .env.prod
      - name: Send docker-compose.prod.yml
        run: |
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" scp -P ${{ secrets.SERVER_PORT }} docker-compose.prod.yml ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/home/learnit/docker-compose/docker-compose.prod.yml
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" scp -P ${{ secrets.SERVER_PORT }} .env.prod ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/home/learnit/docker-compose/.env.prod

      # 18. Deploy with Docker Compose on Remote Server
      - name: Remote Deploy with Docker Compose
        run: |
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh -p ${{ secrets.SERVER_PORT }} ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "
            cd /home/learnit/docker-compose &&
            docker compose --env-file .env.prod -f docker-compose.prod.yml down &&
            docker compose --env-file .env.prod -f docker-compose.prod.yml up -d --build
          "
